language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"

branches:
  only:
    - master

before_script:
  - "npm install"
  - "npm install -g gulp"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com