language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"

branches:
  only:
    - master

before_script:
  - "npm install -g grunt-cli"
  - "npm install"

script:
  - "npm run build"

notifications:
  email:
    - ram@hiddentao.com