language: node_js

node_js:
  - "4"
  - "6"

branches:
  only:
    - master

script:
  - "npm test"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - ram@hiddentao.com
